name: Build and publish Docker image 

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Path to Dockerfile (e.g. docker/azcopy)'
        required: true
      image_name:
        description: 'Image name (e.g. azcopy-test)'
        required: true
      image_version:
        description: 'Image version tag (e.g. v1.0.1)'
        required: true

  push:
    paths:
      - 'docker/**/Dockerfile'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REPO_OWNER }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=${{ inputs.image_version }}
          type=ref,event=branch
          type=sha
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.dockerfile_path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}